[PA] Remove unused kCookie from PartitionAllocDeathTest.SuspendTagCheckingScope
Sample build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-arm64-cast-rel/15347/overview

Sample log:
../../base/allocator/partition_allocator/src/partition_alloc/partition_alloc_unittest.cc:2609:22: error: unused variable 'kCookie' [-Werror,-Wunused-variable]
 2609 |   constexpr uint64_t kCookie = 0x1234567890ABCDEF;
      |                      ^~~~~~~
1 error generated.

Change-Id: I840337a1714b1841428f61fb109270d0502184cf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5747602
Reviewed-by: Keishi Hattori <keishi@chromium.org>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#1334674}
NOKEYCHECK=True
GitOrigin-RevId: b4a8d6fa23f404aa46d5d3b639589f82601b431a