partition_alloc: fix missing `basic_common_reference` in C++17.
A template specialization was introduced by:
https://chromium-review.googlesource.com/c/chromium/src/+/6135992
but it exists only starting from C++20.

In C++17 with Skia embedder, we get the error:
third_party/externals/partition_alloc/src/partition_alloc/pointers/raw_ptr.h:1274:8: error: ‘basic_common_reference’ is not a class template

Bug: 351867706
Change-Id: Id246985a497c5435663642006a5dcbd1466399e3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6276490
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Benoit Lize <lizeb@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1421052}
NOKEYCHECK=True
GitOrigin-RevId: e6fc4c741cc17913338c2ba5978c659d1b0cec1c