[shim] Move kPartitionAllocDispatch into another header file.
allocator_shim_default_dispatch_to_partition_alloc.h is included by
other components. So if is_component_build=true and is_win=true,
PartitionMalloc(), PartitionUncheckedMalloc(), and so on are
DLL-exported functions. Inside allocator_shim, a compiler knows
the symbols. But regarding other components, need to import the
symbols from allocator_shim.dll. The symbols are not constexpr.
We will see the following error:
---
In file included from ../../base/trace_event/malloc_dump_provider.cc:44:
../../base/allocator/partition_allocator/src\partition_alloc/shim/allocator_shim_default_dispatch_to_partition_alloc.h(136,36): error: constexpr variable 'kPartitionAllocDispatch' must be initialized by a constant expression
  136 | inline constexpr AllocatorDispatch kPartitionAllocDispatch = {
      |                                    ^                         ~
  137 |     &allocator_shim::internal::PartitionMalloc,  // alloc_function
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  138 |     &allocator_shim::internal::
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
---
malloc_dump_provider.cc is a part of base component's, i.e. base.dll.

To fix the issue, we should not expose kPartitionAllocDispatch to
other components, because only allocator_shim needs it.

Bug: 351974425
No-Try: true

Change-Id: I117704fa20ed0cd5dd44df8a5afd52e5a89db217
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5772611
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Mikihito Matsuura <mikt@google.com>
Cr-Commit-Position: refs/heads/main@{#1339551}
NOKEYCHECK=True
GitOrigin-RevId: 37aad0a446fe8efe9a75e5a21fbd4e7deb2dbdb2